# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The 
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /hello:
    get:
      summary: This is just a test endpoint to get you started. Please delete this endpoint.
      operationId: hello
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Test return
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /register:
    post:
      summary: This is endpoint for register
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterPayload'
      responses:
        '200':
          description: PostRegisterResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              examples:
                invalidPhoneNumber:
                  value:
                    message: "Invalid phone number. Please provide a valid Indonesian phone number starting with '+62'."
                invalidPassword:
                  value:
                    message: "Invalid password. Please provide a password with at least 6 characters, including 1 capital letter, 1 number, and 1 special character."
                invalidFullName:
                  value:
                    message: "Invalid full name. Please provide a valid full name."
  /update:
    put:
      summary: This is endpoint for update
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePayload'
      responses:
        '200':
          description: UpdateResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateResponse'
  /profile:
    get:
      summary: This is endpoint for get profile
      operationId: profile
      responses:
        '200':
          description: ProfileResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
components:
  schemas:
    HelloResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    RegisterPayload:
      type: object
      required:
        - phone_number
        - password
        - full_name
      properties:
        phone_number:
          type: string
        password:
          type: string
          format: password
        full_name:
          type: string
    RegisterResponse:
      type: object
      required:
        - message
        - id
      properties:
        message:
          type: string
        id:
          type: integer
    UpdatePayload:
      type: object
      required:
        - phone_number
        - full_name
      properties:
        phone_number:
          type: string
        full_name:
          type: string
    UpdateResponse:
      type: object
      required:
        - message
        - data
      properties:
        message:
          type: string
        data:
          type: object
          required:
            - phone_number
            - full_name
          properties:
            phone_number:
              type: string
            full_name:
              type: string
    ProfileResponse:
      type: object
      required:
        - phone_number
        - full_name
      properties:
        phone_number:
          type: string
        full_name:
          type: string